### ISSUE TITLE
subscription support

### ISSUE THREAD

**Issue by ericmelvin** [axtiva/flexible-graphql-php#21]
I see the README says: Support all features from webonyx/graphql-php

Has subscription support been added?  I haven't seen it in the change logs.

**Comment by bpteam** [comment]
Hello, @ericmelvin !

Last version of [webonyx/graphql-php does not support subscription](https://webonyx.github.io/graphql-php/schema-definition/#configuration-options). Coud you share link to implementatio of Subscription into webonyx/graphql-php?

Thanks for interesting to library.
